In [1]:
class MyGRU(layers.Layer):
    def __init__(self, *args, **kwargs):
        super(MyGRU, self).__init__()
        self.gru = layers.GRU(*args, **kwargs)
        
    @tf.function
    def call(self, sequences, seq_lengths):
        mask = tf.sequence_mask(seq_lengths)
        output = self.gru(sequences, mask=mask)  # The layer will ignore the masked values
        return output

NameError: name 'layers' is not defined

In [5]:
indices = tf.constant([[4], [3], [1], [7]])
indices

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[4],
       [3],
       [1],
       [7]], dtype=int32)>

In [6]:
updates = tf.constant([9, 10, 11, 12])
updates

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 9, 10, 11, 12], dtype=int32)>

In [7]:
tensor = tf.ones([8], dtype=tf.int32)
tensor

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)>

In [8]:
tf.tensor_scatter_nd_update(tensor, indices, updates)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 1, 11,  1, 10,  9,  1,  1, 12], dtype=int32)>

In [15]:
indices = tf.constant([[0], [2]])
indices

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[0],
       [2]], dtype=int32)>

In [14]:
updates = tf.constant([[[5, 5, 5, 5], [6, 6, 6, 6],
                            [7, 7, 7, 7], [8, 8, 8, 8]],
                           [[5, 5, 5, 5], [6, 6, 6, 6],
                            [7, 7, 7, 7], [8, 8, 8, 8]]])
updates

<tf.Tensor: shape=(2, 4, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]],

       [[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]]], dtype=int32)>

In [16]:
updates = tf.fill([2,4,4], 9)
updates

<tf.Tensor: shape=(2, 4, 4), dtype=int32, numpy=
array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]], dtype=int32)>

In [13]:
tensor = tf.ones([4, 4, 4], dtype=tf.int32)
tensor

<tf.Tensor: shape=(4, 4, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [21]:
tf.tensor_scatter_nd_update(tensor, indices, updates)

<tf.Tensor: shape=(4, 4, 4), dtype=int32, numpy=
array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [23]:
tensor = tf.range(60)
tensor

<tf.Tensor: shape=(60,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59], dtype=int32)>

In [25]:
tensor = tf.reshape(tensor, [2, 5, 6])
tensor

<tf.Tensor: shape=(2, 5, 6), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]]], dtype=int32)>

In [37]:
indices = [[0, 1], [1, 1]]

tf.gather_nd(tensor ,indices)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 6,  7,  8,  9, 10, 11],
       [36, 37, 38, 39, 40, 41]], dtype=int32)>