In [99]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [4]:
tf.add(1,2).numpy()

3

In [5]:
x = keras.Input(shape=(2,))
y = tf.add(x, 1)

In [7]:
model = keras.Model(x, y)

In [16]:
a = tf.constant([[1,2], [2,3], [4,5]])
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [4, 5]], dtype=int32)>

In [17]:
model(a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 3.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [83]:
x = keras.Input(shape=())

In [84]:
x

<tf.Tensor 'input_5:0' shape=(None,) dtype=float32>

In [85]:
y = tf.multiply(x, 2)

In [86]:
y

<tf.Tensor 'Mul_3:0' shape=(None,) dtype=float32>

In [87]:
model = keras.Model(x, y)

In [88]:
model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None,)]                 0         
_________________________________________________________________
tf_op_layer_Mul_3 (TensorFlo [(None,)]                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [95]:
a = tf.constant([2, 3, 4, 4, 5, 6])

In [96]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 4, 5, 6], dtype=int32)>

In [97]:
model(a)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 4.,  6.,  8.,  8., 10., 12.], dtype=float32)>

In [113]:
batch_size = 1
time_step = 10    
signal_length = 10
sequences = np.random.rand(batch_size, time_step, 1)
seq_lengths = np.array([signal_length])
signal_mask = np.random.randint(5, size=(1, time_step))

dataset = tf.data.Dataset.from_tensor_slices(
        ((sequences, seq_lengths),  signal_mask)).repeat(2).batch(1)

In [114]:
for r in dataset:
    print(r)

((<tf.Tensor: shape=(1, 10, 1), dtype=float64, numpy=
array([[[0.48190306],
        [0.30611332],
        [0.25350495],
        [0.35268335],
        [0.12751846],
        [0.82484004],
        [0.51899576],
        [0.03258738],
        [0.69107689],
        [0.7608703 ]]])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([10])>), <tf.Tensor: shape=(1, 10), dtype=int64, numpy=array([[2, 1, 2, 2, 3, 1, 3, 3, 4, 0]])>)
((<tf.Tensor: shape=(1, 10, 1), dtype=float64, numpy=
array([[[0.48190306],
        [0.30611332],
        [0.25350495],
        [0.35268335],
        [0.12751846],
        [0.82484004],
        [0.51899576],
        [0.03258738],
        [0.69107689],
        [0.7608703 ]]])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([10])>), <tf.Tensor: shape=(1, 10), dtype=int64, numpy=array([[2, 1, 2, 2, 3, 1, 3, 3, 4, 0]])>)
